### ISSUE TITLE
What's the reason behind `zodbpickle.binary`?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zodbpickle#38]
The code says it is there for converting binary data to Python 3. I tried it and failed:

**Python 2.7:**

```python
>>> import pickle, pickletools, zodbpickle
>>> pickle.dumps(zodbpickle.binary('a'))
"ccopy_reg\n_reconstructor\np0\n(czodbpickle\nbinary\np1\nc__builtin__\nstr\np2\nS'a'\np3\ntp4\nRp5\n."
>>> pickletools.dis(pickle.dumps(zodbpickle.binary('a')))
    0: c    GLOBAL     'copy_reg _reconstructor'
   25: p    PUT        0
   28: (    MARK
   29: c        GLOBAL     'zodbpickle binary'
   48: p        PUT        1
   51: c        GLOBAL     '__builtin__ str'
   68: p        PUT        2
   71: S        STRING     'a'
   76: p        PUT        3
   79: t        TUPLE      (MARK at 28)
   80: p    PUT        4
   83: R    REDUCE
   84: p    PUT        5
   87: .    STOP
highest protocol among opcodes = 0
```

Trying to read this pickle on **Python 3** failed:

```python
>>> import pickle, pickletools, zodbpickle
>>> pickle.loads(b"ccopy_reg\n_reconstructor\np0\n(czodbpickle\nbinary\np1\nc__builtin__\nstr\np2\nS'a'\np3\ntp4\nRp5\n.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copyreg.py", line 45, in _reconstructor
    obj = base.__new__(cls, state)
TypeError: str.__new__(bytes): bytes is not a subtype of str
str.__new__(bytes): bytes is not a subtype of str
```

The reason seems to be that the base class`str` from Python 2 is still `str` (see the `dis` in Python 3):

```python
>>> pickletools.dis(b"ccopy_reg\n_reconstructor\np0\n(czodbpickle\nbinary\np1\nc__builtin__\nstr\np2\nS'a'\np3\ntp4\nRp5\n.")
    0: c    GLOBAL     'copy_reg _reconstructor'
   25: p    PUT        0
   28: (    MARK
   29: c        GLOBAL     'zodbpickle binary'
   48: p        PUT        1
   51: c        GLOBAL     '__builtin__ str'
   68: p        PUT        2
   71: S        STRING     'a'
   76: p        PUT        3
   79: t        TUPLE      (MARK at 28)
   80: p    PUT        4
   83: R    REDUCE
   84: p    PUT        5
   87: .    STOP
highest protocol among opcodes = 0
```

It gets even worse when trying to unpickle a non-ASCII Python 2 string:

```python
>>> pickle.dumps(zodbpickle.binary('ä'))
"ccopy_reg\n_reconstructor\np0\n(czodbpickle\nbinary\np1\nc__builtin__\nstr\np2\nS'\\xc3\\xa4'\np3\ntp4\nRp5\n."
```

Trying to read it in Python 3 results in:

```python
>>> pickle.loads(b"ccopy_reg\n_reconstructor\np0\n(czodbpickle\nbinary\np1\nc__builtin__\nstr\np2\nS'\\xc3\\xa4'\np3\ntp4\nRp5\n.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

What am I doing wrong? Which pice of the puzzle am I missing?

**Comment by jamadden** [comment]
I believe that the answer was to use `zodbpickle` to do the pickling also. That does produce different pickles than using the stdlib `pickle`, under all protocol versions.

Python 2.7:
```pycon
In [1]: import zodbpickle

In [3]: from zodbpickle import fastpickle

In [4]: fastpickle.dumps(zodbpickle.binary(b'a'), 3)
Out[4]: '\x80\x03C\x01a.'

In [5]: fastpickle.dumps(zodbpickle.binary(b'a'), 2)
Out[5]: '\x80\x02c_codecs\nencode\nq\x01X\x01\x00\x00\x00aU\x06latin1q\x02\x86R.'

In [6]: fastpickle.dumps(zodbpickle.binary(b'a'), 1)
Out[6]: 'c_codecs\nencode\nq\x01(X\x01\x00\x00\x00aU\x06latin1q\x02tR.'

In [7]: import pickle

In [8]: pickle.dumps(zodbpickle.binary(b'a'))
Out[8]: "ccopy_reg\n_reconstructor\np0\n(czodbpickle\nbinary\np1\nc__builtin__\nstr\np2\nS'a'\np3\ntp4\nRp5\n."

In [10]: pickle.dumps(zodbpickle.binary(b'a'), 2)
Out[10]: '\x80\x02czodbpickle\nbinary\nq\x00U\x01aq\x01\x85q\x02\x81q\x03}q\x04b.'
```

These pickles can be read under Python 3.6 with zodbpickle:
```pycon
In [1]: from zodbpickle import fastpickle

In [2]: fastpickle.loads(b'\x80\x03C\x01a.') # 3
Out[2]: b'a'

In [3]: fastpickle.loads(b'\x80\x02c_codecs\nencode\nq\x01X\x01\x00\x00\x00aU\x06latin1q\x02\x86R.') # 2
Out[3]: b'a'

In [4]: fastpickle.loads(b'c_codecs\nencode\nq\x01(X\x01\x00\x00\x00aU\x06latin1q\x02tR.') # 1
Out[4]: b'a'
```

And regular pickle:
```pycon
In [7]: import pickle

In [8]: pickle.loads(b'\x80\x03C\x01a.')
Out[8]: b'a'
```

**Comment by icemac** [comment]
@jamadden Thank you for your explanation. This was the missing piece.
But it means I have to search somewhere else to find out why replacing `str` by `zodbpickle.binary` via [zodb.py3migrate](https://github.com/gocept/zodb.py3migrate) in an actual ZODB does not work. I get there a `UnicodeDecodeError` like the one shown above for the non-ASCII string.
